version: '3.7'

services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend/
        image: app/frontend
        volumes:
            - ./frontend/:/app
            - /app/node_modules
        ports:
            - 3000:3000
        env_file:
            - .env
        depends_on:
            - backend

    backend:
        container_name: backend
        build:
            context: ./backend/
        image: app/backend
        volumes:
            - ./backend/:/app
            - /app/node_modules
        ports:
            - 5000:5000
            - 5555:5555
        env_file:
            - .env
        depends_on:
            - db
    db:
        container_name: db
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE_NAME}
            PG_DATA: /var/lib/postgresql/data
        ports:
            - 5432:5432
volumes:
    PG_DATA: